import socket
import os

''' AUTOGENERATED BY CHATGPT '''

def start_client(filename: str):
    client_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    client_socket.connect(('localhost', 65432))  # Connect to the server at localhost:65432
    
    # sending binary file
    chunk = None
    with open(filename, 'rb') as file:
        while (chunk := file.read(4096)):
            client_socket.sendall(chunk)  # Send a message to the server
    
    ON = True
    while ON:
        command = sendCommand()
        # shut server off
        if command == 'q':
            print('Shutting down client...')
            ON = False
            client_socket.close()
            break
        elif command == '@':
            client_socket.sendall('haaaaaaaay bitch'.encode())
        else:
            print('invalid command received')

    # try-catch block.
    try:    
        # TRY TO DO THIS 
        data = client_socket.recv(1024)  # Receive the response from the server
        print(f"Received from server: {data.decode()}")
    # and if an error is thrown (errors can be referred to as EXCEPTIONS)...
    except OSError:
        # DO THIS.
        print('Connection to server already closed. Or something else went wrong...')
    
    client_socket.close()  # Close the connection


def sendCommand():

    commandedMessage = input('Enter a command')

    return commandedMessage

if __name__ == "__main__":
    filename = 'lease.pdf'
    if filename in os.listdir():
        start_client(filename)
    else:
        print('error')
